version: '3.8'

services:
  mcp-run-python-code:
    build: .
    container_name: mcp-run-python-code-server
    restart: unless-stopped
    volumes:
      # Optional: Mount local code for development/testing
      # - ./code_execution:/tmp/code_execution
      # Optional: Mount logs directory
      # - ./logs:/var/log
    environment:
      # Set base directory for code execution (optional)
      # BASE_DIR: /tmp/code_execution
      # Set log level (optional)
      # LOG_LEVEL: INFO
    stdin_open: true
    tty: true
    # MCP servers typically use stdio transport, so we need to run in interactive mode
    command: ["mcp-run-python-code"]